on:
  workflow_dispatch:
    inputs:
      appendText:
        description: Text to append to the posted message
jobs:
  post:
    name: Publish to Slack
    runs-on: ubuntu-latest
    steps:
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
        payload: |
          {
            "text": "**GitHub Action** _message_!\n${{ inputs.appendText }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "**GitHub Action** _message_!\n${{ inputs.appendText }}"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
